export const enum KAI_PAGES {
    DATA_CUSTOMERS = '/pages/kai/customers',
    DATA_PURCHASING_INVOICES = '/pages/kai/purchasing-invoices',
    DATA_PRODUCTS = '/pages/kai/products',
    DATA_PENDING_ORDERS = '/pages/kai/pending-orders',
    DATA_PENDING_ORDERS_JP = '/pages/kai/pending-orders-jp',
    DATA_PENDING_ORDERS_VN = '/pages/kai/pending-orders-vn',
    DATA_PENDING_ORDERS_WAREHOUSE = '/pages/kai/pending-orders-warehouse',
    DATA_COMPLETED_ORDERS = '/pages/kai/completed-orders',
    DATA_COMPLETED_ORDERS_JP = '/pages/kai/completed-orders-jp',
    DATA_COMPLETED_ORDERS_VN = '/pages/kai/completed-orders-vn',
    DATA_COMPLETED_ORDERS_WAREHOUSE = '/pages/kai/completed-orders-warehouse',
    DATA_DEVICES = '/pages/kai/devices',
    DATA_OUTGOING_TRANSFER_PRODUCTS = '/pages/kai/outgoing-transfer/products',
    STATISTICS = '/pages/kai/statistics',
    CUSTOMER = '/pages/kai/customer',
    PURCHASING_INVOICE = '/pages/kai/invoice',
}
